import Sidebar from '../../components/dashboard/Sidebar';
import CreateCourse from '../../components/dashboard/CreateCourse';
import Head from 'next/head';
import { useRouter } from 'next/router';

export default function Dashboard({ categories }) {
	const { query } = useRouter();

	return (
		<div>
			<Head>
				<title>Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="lg:flex  ">
				<Sidebar />

				<main className="flex-1 bg-gray-50  ">
					<CreateCourse />
					{/* {query.query === 'create-course' && <CreateCourse />} */}
					{/* {query.query === 'create-resource' && <CreateResource />}
					{query.query === 'create-category' && <AddCategory />}
					{query.query === 'product-list' && <ProductList />} */}
				</main>
			</div>
		</div>
	);
}

// export async function getServerSideProps() {
// 	await dbConnect();
// 	const res = await Category.find({});
// 	const cat = JSON.parse(JSON.stringify(res));

// 	return {
// 		props: { categories: cat }
// 	};
// }
